---
title: "QMM Assignment 1"
author: "Bharadwaj Yedhagiri"
date: '09-08-2024'
output:
  pdf_document: default
  html_document: default
---
Question 1\
a.\
Decision variables\
The choice variables in this problem are two distinct bag models. They are Mini and Collegiate. We'll refer to them as follows.
$$ Collegiate bag = X_a$$\
$$ Mini bag =X_b$$
b.\
objective function\
A profit of 32dollar is made from each Collegiate bag, and a profit of 24dollar from each Mini backpack.
$$ Maximize(Profit) Z=32X_a+24X_b $$
c.\
Constraints\
In this problem, we have two different kinds of constraints. They're\
Labor constraints: $$ 45X_a + 40X_b \le (35)(40)(60)$$\
It takes 45 minutes to labor each Collegiate and 40 minutes to labor each Mini.


Material constraint: $$ 3X_a + 2X_b \le 5000$$\
Three square feet are used by each Collegiate and two square feet by each Mini.

Non negativity : \
$$ X_a,X_b\ge 0$$\
$$X_a\le 1000$$\
$$X_b\le 1200$$\



d.\
Full mathematical formulation\
$$ Max \hspace{.2cm}  Z=32X_a+24X_b $$
 $$ 45X_a + 40X_b \le (35)(40)(60)$$\
 $$ 3X_a + 2X_b \le 5000$$\
 $$ X_a,X_b\ge 0$$\
$$X_a\le 1000$$\
$$X_b\le 1200$$\

 \
 \
\
Question 2:\
a. Decision variables\
$$L_n = number\hspace{.2cm} of\hspace{.2cm} large\hspace{.2cm} shirts\hspace{.2cm} produced\hspace{.2cm} in\hspace{.2cm} nth\hspace{.2cm} plant $$\
$$M_n = number\hspace{.2cm} of\hspace{.2cm} medium\hspace{.2cm} shirts\hspace{.2cm} produced\hspace{.2cm} in\hspace{.2cm} nth\hspace{.2cm} plant $$\
$$S_n = number\hspace{.2cm} of\hspace{.2cm} small\hspace{.2cm} shirts\hspace{.2cm} produced\hspace{.2cm} in\hspace{.2cm} nth\hspace{.2cm} plant $$\
where n=1,2,3.\




b. LP Model\
objective function :\
$$ Maximize\hspace{.2cm}Z = 420(L_1+L_2+L_3) + 360(M_1+M_2+M_3) + 300(S_1+S_2+S_3)$$\


Constraints\
capacity constraint:\
$$ L_1+M_1+S_1\le 750$$\
$$l_2+M_2+S_2\le 900$$\
$$L_3+M_3+S_3\le 450$$\


storage constraints:\
$$20L_1+15M_1+12S_1\le 13000 $$\
$$20L_2+15M_2+12S_2\le 12000 $$\
$$20L_3+15M_3+12S_3\le 5000 $$\


sales constraint:\
$$L_1+L_2+L_3\le 900$$\
$$M_1+M_2+M_3\le 1200$$\
$$S_1+S_2+S_3\le 750$$\

constraints to avoid lay off's
$$(L_1+M_1+S_1)*(100/750)=(L_2+M_2+S_2)*(100/900)=(L_3+M_3+S_3)*(100/450)$$\

Non negativity : 
$$ L_1,L_2,L_3\ge 0$$\
$$M_1,M_2,M_2\ge 0$$\
$$S_1,S_2,S_3\ge 0$$\

